# Array Input and Output.

In [12]:
import numpy as np

In [13]:
arr = np.arange(5)
np.save('my_array',arr)
arr1 = np.load('my_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [14]:
arr = np.arange(5)
arr1 = np.arange(10)
np.savez('two_arrays.npz',x=arr,y=arr1)
arr_ = np.load('two_arrays.npz')
print(arr_['x'])
arr_['y']

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#saving and loading text files
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])