In [1]:
import numpy as np

In [24]:
# create array
np.array([1,2,3])
print(np.ones([5,5]))
print(np.zeros([1,2,3,4]))
print(np.eye(5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [69]:
# Indexing array

a = np.arange(30).reshape(3,-1)
print(a)
print(a[1:,:3])
#
b = np.arange(100).reshape(5,-1)
print(b)
b[[3,4,1]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[10 11 12]
 [20 21 22]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [75]:
# array transform

a = np.arange(50).reshape(5,-1)
print(a.T)

#dot
print(np.dot(a,a.T))

[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]
[[  285   735  1185  1635  2085]
 [  735  2185  3635  5085  6535]
 [ 1185  3635  6085  8535 10985]
 [ 1635  5085  8535 11985 15435]
 [ 2085  6535 10985 15435 19885]]


In [86]:
# Array funtion

A = np.random.randn(10)
B = np.random.randn(10)
print('A is :'+'\n'+str(A))
print('B is :'+'\n'+str(B))

# binary funtion 
print(np.add(A,B))
print(np.maximum(A,B))

A is :
[ 0.89738716  0.16184505  1.56543065 -0.463065    0.45224721  1.71884827
  1.18704695 -0.87143998  1.30260343  2.5204849 ]
B is :
[ 1.57958847 -1.26276668  0.3326988   0.7350506  -0.09974638  0.88589781
 -0.95098414 -0.18702084  0.12891453 -1.1263839 ]
[ 2.47697563 -1.10092164  1.89812945  0.2719856   0.35250083  2.60474608
  0.23606282 -1.05846082  1.43151795  1.39410099]
[ 1.57958847  0.16184505  1.56543065  0.7350506   0.45224721  1.71884827
  1.18704695 -0.18702084  1.30260343  2.5204849 ]


In [90]:
# numpy where

a = np.array([1,2,3,4])
b = np.array([500,600,700,800])
condition = np.array([True,False,True,False])

answer = [(a_v if cond else b_v) for a_v,b_v,cond in zip(a,b,condition)]
print(answer)

# 
answer2 = np.where(condition,a,b)
answer2

[1, 600, 3, 800]


array([  1, 600,   3, 800])

In [92]:
a = np.random.randn(5,5)
answer = np.where(a>0,0,a)
answer

array([[ 0.        , -0.84002478, -1.16281731,  0.        ,  0.        ],
       [-1.27876533,  0.        , -0.36990648, -0.45020055,  0.        ],
       [-1.1109197 ,  0.        ,  0.        ,  0.        , -0.45694368],
       [ 0.        , -1.45578248, -1.20820615, -1.68744754,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.23082897, -0.37823502]])

In [99]:
# numpy sum
a = np.arange(1,13).reshape(3,-1)
print(a)
print(a.sum())
print(a.sum(0))
print(a.sum(1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


In [105]:
# np.unique
fruit = np.array(['apple','bannana','lemon','apple'])
print(np.unique(fruit))
np.in1d(['apple','lemon','orange'],fruit)

['apple' 'bannana' 'lemon']


array([ True,  True, False])